development: &development
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: blinkbox
  suffix: files
  username:
  password:

test:
  <<: *development
  suffix: test

production:
  protocol: 'https'
  host: localhost
  port: 5984
  prefix: blinkbox
  suffix: files_production
  username: root
  password: 123
