development: &development
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: blinkbox_files
  suffix: development

test:
  <<: *development
  suffix: test

production:
  protocol: 'http'
  host: <%= ENV['DB_URL'] %>
  port: <%= ENV['DB_PORT'] %>
  prefix: blinkbox_files
